# Generated by Django 2.0.1 on 2018-02-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipal_tax', models.DecimalField(decimal_places=2, help_text='Taxes Levied by BMC', max_digits=10)),
                ('maintenance', models.DecimalField(decimal_places=2, help_text='Maintenance Charges', max_digits=10)),
                ('water_charges', models.DecimalField(decimal_places=2, help_text='Water Costs', max_digits=10)),
                ('parking_charges', models.DecimalField(decimal_places=2, help_text='Car/Scooter/Stilt', max_digits=10)),
                ('sinking_fund', models.DecimalField(decimal_places=2, help_text='Sinking Fund', max_digits=10)),
                ('building_repair', models.DecimalField(decimal_places=2, help_text='Fund for Building Repairs', max_digits=10)),
                ('elec_insurance_charges', models.DecimalField(decimal_places=2, help_text='Electricity Insurance', max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Billing Details',
            },
        ),
    ]
