# Generated by Django 2.2.12 on 2020-05-21 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_type', models.CharField(default='3', help_text='Your Choices are 1, 2, 3.', max_length=1)),
                ('municipal_tax', models.DecimalField(decimal_places=2, help_text='Taxes Levied by BMC', max_digits=10)),
                ('maintenance', models.DecimalField(decimal_places=2, help_text='Maintenance Charges', max_digits=10)),
                ('water_charges', models.DecimalField(decimal_places=2, help_text='Water Costs', max_digits=10)),
                ('parking_charges', models.DecimalField(decimal_places=2, help_text='Car/Scooter/Stilt', max_digits=10)),
                ('sinking_fund', models.DecimalField(decimal_places=2, help_text='Sinking Fund', max_digits=10)),
                ('building_repair', models.DecimalField(decimal_places=2, help_text='Fund for Building Repairs', max_digits=10)),
                ('elec_ins_chgs', models.DecimalField(decimal_places=2, help_text='Electricity Insurance', max_digits=10, verbose_name='Electricity Insurance Charges')),
            ],
            options={
                'verbose_name_plural': 'Billing Details',
            },
        ),
        migrations.CreateModel(
            name='FlatBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField(auto_now_add=True, verbose_name='Bill Date')),
                ('municipal_tax', models.DecimalField(decimal_places=2, help_text='Taxes Levied by BMC', max_digits=10)),
                ('maintenance', models.DecimalField(decimal_places=2, help_text='Maintenance Charges', max_digits=10)),
                ('water_charges', models.DecimalField(decimal_places=2, help_text='Water Costs', max_digits=10)),
                ('parking_charges', models.DecimalField(decimal_places=2, help_text='Car/Scooter/Stilt', max_digits=10)),
                ('sinking_fund', models.DecimalField(decimal_places=2, help_text='Sinking Fund', max_digits=10)),
                ('building_repair', models.DecimalField(decimal_places=2, help_text='Fund for Building Repairs', max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('elec_ins_chgs', models.DecimalField(decimal_places=2, help_text='Electricity Insurance', max_digits=10, verbose_name='Electricity Insurance Charges')),
                ('noc_charges', models.DecimalField(decimal_places=2, default=0, help_text='Non Occupancy Charges', max_digits=10, verbose_name='N.O.C. Charges')),
                ('add_item_name_1', models.CharField(blank=True, max_length=100, verbose_name='Additional Items e.g. Building Maintenance')),
                ('add_item_name_2', models.CharField(blank=True, max_length=100, verbose_name='Additional Items e.g. Emergency_fund')),
                ('add_item_amt_1', models.DecimalField(decimal_places=2, default=0, help_text='Amount for Additional Item 1', max_digits=10)),
                ('add_item_amt_2', models.DecimalField(decimal_places=2, default=0, help_text='Amount for Additional Item 2', max_digits=10)),
                ('flat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Flat')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_on', models.DateField()),
                ('payment_mode', models.CharField(help_text='Cheque, Bank Transfer etc.', max_length=200)),
                ('drawn_on', models.CharField(help_text='Financial institution received from.', max_length=250)),
                ('transaction_no', models.CharField(help_text='Cheque Number or Bank Transfer Number.', max_length=250)),
                ('received_amount', models.DecimalField(decimal_places=2, help_text='Amount Received from Member.', max_digits=25)),
                ('related_bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billing.FlatBill')),
            ],
        ),
    ]
