# Generated by Django 2.0.1 on 2018-02-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetails',
            name='flat_type',
            field=models.CharField(default='3', help_text='Your Choices are 1, 2, 3.', max_length=1),
        ),
    ]
