# Generated by Django 2.0.1 on 2018-02-07 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180206_0417'),
        ('billing', '0003_auto_20180207_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField(auto_now=True, verbose_name='Bill Date')),
                ('municipal_tax', models.DecimalField(decimal_places=2, help_text='Taxes Levied by BMC', max_digits=10)),
                ('maintenance', models.DecimalField(decimal_places=2, help_text='Maintenance Charges', max_digits=10)),
                ('water_charges', models.DecimalField(decimal_places=2, help_text='Water Costs', max_digits=10)),
                ('parking_charges', models.DecimalField(decimal_places=2, help_text='Car/Scooter/Stilt', max_digits=10)),
                ('sinking_fund', models.DecimalField(decimal_places=2, help_text='Sinking Fund', max_digits=10)),
                ('building_repair', models.DecimalField(decimal_places=2, help_text='Fund for Building Repairs', max_digits=10)),
                ('elec_ins_chgs', models.DecimalField(decimal_places=2, help_text='Electricity Insurance', max_digits=10, verbose_name='Electricity Insurance Charges')),
                ('flat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Flat')),
            ],
        ),
    ]
