# Generated by Django 2.0.1 on 2018-02-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_flatbill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatbill',
            old_name='flat_type',
            new_name='flat_name',
        ),
    ]
