# Generated by Django 2.0.2 on 2018-02-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20180213_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatbill',
            name='noc_charges',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Non Occupancy Charges', max_digits=10, verbose_name='N.O.C. Charges'),
        ),
    ]
