# Generated by Django 2.0.1 on 2018-02-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_flatbill_noc_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatbill',
            name='add_item_name_1',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Additional Items e.g. Building Maintenance'),
        ),
        migrations.AlterField(
            model_name='flatbill',
            name='add_item_name_2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Additional Items e.g. Emergency_fund'),
        ),
    ]
