# Generated by Django 2.0.1 on 2018-02-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_auto_20180214_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatbill',
            name='add_item_name_1',
            field=models.CharField(default='', max_length=100, verbose_name='Additional Items e.g. Building Maintenance'),
        ),
        migrations.AlterField(
            model_name='flatbill',
            name='add_item_name_2',
            field=models.CharField(default='', max_length=100, verbose_name='Additional Items e.g. Emergency_fund'),
        ),
    ]
