# Generated by Django 2.0.1 on 2018-02-26 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20180214_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_on', models.DateField()),
                ('payment_mode', models.CharField(help_text='Cheque, Bank Transfer etc.', max_length=200)),
                ('drawn_on', models.CharField(help_text='Financial institution received from.', max_length=250)),
                ('transaction_no', models.CharField(help_text='Cheque Number or Bank Transfer Number.', max_length=250)),
                ('related_bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billing.FlatBill')),
            ],
        ),
    ]
