# Generated by Django 2.0.1 on 2018-02-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount Received from Member.', max_digits=25),
            preserve_default=False,
        ),
    ]
