# Generated by Django 2.0.1 on 2018-04-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_receipt_received_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatbill',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
