# Generated by Django 2.0.1 on 2018-04-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_flatbill_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatbill',
            name='bill_date',
            field=models.DateField(auto_now_add=True, verbose_name='Bill Date'),
        ),
    ]
