# Generated by Django 2.0.1 on 2018-02-05 16:17

from django.db import migrations, models
import django.db.models.deletion
import members.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(max_length=3, validators=[members.validators.number_validator], verbose_name='Flat Number')),
                ('wing', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=10, validators=[members.validators.mobile_validator])),
                ('flat_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.Flat')),
            ],
        ),
    ]
