# Generated by Django 2.2.12 on 2020-05-21 17:58

from django.db import migrations, models
import django.db.models.deletion
import members.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(max_length=3, validators=[members.validators.number_validator], verbose_name='Flat Number')),
                ('wing', models.CharField(max_length=1)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'unique_together': {('flat_number', 'wing')},
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(choices=[('TWST', 'Two Wheeler Stilt'), ('FWST', 'Four Wheeler Stilt'), ('TWOU', 'Two Wheeler Outside'), ('FWOU', 'Four Wheeler Outside')], max_length=4)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Flat')),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=10, validators=[members.validators.mobile_validator])),
                ('flat_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.Flat')),
            ],
        ),
        migrations.CreateModel(
            name='RentalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rented', models.BooleanField(default=False)),
                ('flat_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.Flat')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=10, validators=[members.validators.mobile_validator])),
                ('flat_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.Flat')),
            ],
        ),
    ]
