# Generated by Django 2.0.1 on 2018-03-29 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180206_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rented', models.BooleanField(default=False)),
                ('flat_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.Flat')),
            ],
        ),
    ]
