# Generated by Django 2.0.1 on 2018-03-29 15:19

from django.db import migrations, models
import django.db.models.deletion
import members.validators


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rentalstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=10, validators=[members.validators.mobile_validator])),
                ('flat_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.Flat')),
            ],
        ),
    ]
